apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart-rolebinding
  namespace: eiffeltower
subjects:
- kind: ServiceAccount
  name: cronjob-sa
  namespace: eiffeltower
roleRef:
  kind: Role
  name: deployment-restart-role
  apiGroup: rbac.authorization.k8s.io
