apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: infra
  name: deployment-restart-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
  resourceNames: ["eiffeltower"]
