---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: eiffeltower
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch", "restart"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: eiffeltower
subjects:
- kind: ServiceAccount
  name: cronjob-sa
  namespace: infra
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: greatwall
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch", "restart"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: greatwall
subjects:
- kind: ServiceAccount
  name: cronjob-sa
  namespace: infra
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: liberty
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch", "restart"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: liberty
subjects:
- kind: ServiceAccount
  name: cronjob-sa
  namespace: infra
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: tajmahal
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch", "restart"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: tajmahal
subjects:
- kind: ServiceAccount
  name: cronjob-sa
  namespace: infra
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io 